version: '2'
services:
    config-server:
        container_name: config-server
        build:
            context: .
            dockerfile: ./config-server/config-server/Dockerfile
        image: config-server:latest
        expose:
            - 9003
        ports:
            - 9003:9003
        logging:
            driver: json-file
        depends_on:
            - eureka-server
        networks:
            - spring-cloud-network
        links:
            - eureka-server:eureka-server
        hostname: 'config-server'    
        environment: 
            # Important for clients to register with eureka
            - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

    eureka-server:
        container_name: eureka-server
        build:
            context: .
            dockerfile: ./eureka-server/Dockerfile
        image: eureka-server:latest
        expose:
            - 8761
        ports:
            - 8761:8761
        logging:
            driver: json-file
        networks:
            - spring-cloud-network
        hostname: 'eureka-server'

    gateway-api:
        container_name: gateway-api
        build:
            context: .
            dockerfile: ./gateway-api/Dockerfile
        image: gateway-api:latest
        expose:
            - 9191
        ports:
            - 9191:9191
        depends_on:
            - config-server
            - eureka-server
        logging:
            driver: json-file
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
            - eureka-server:eureka-server
        hostname: 'gateway-api'
        environment: 
            # Important for clients to register with eureka
            - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            - spring.cloud.config.uri=http://config-server:9003

    parking-service:
        container_name: parking-service
        build:
            context: .
            dockerfile: ./parking-service/Dockerfile
        image: parking-service:latest
        expose:
            - 9001
        ports:
            - 9001:9001
        depends_on:
            - config-server
            - eureka-server
            - gateway-api
        logging:
            driver: json-file
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
            - eureka-server:eureka-server
            - gateway-api:gateway-api
        hostname: 'PARKING-SERVICE'
        environment: 
            # Important for clients to register with eureka
            - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            - spring.cloud.config.uri=http://config-server:9003

    route-service:
        container_name: route-service
        build:
            context: .
            dockerfile: ./route-service/Dockerfile
        image: route-service:latest
        expose:
            - 9002
        ports:
            - 9002:9002
        depends_on:
            - config-server
            - eureka-server
            - gateway-api
        logging:
            driver: json-file
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
            - eureka-server:eureka-server
            - gateway-api:gateway-api
        hostname: 'ROUTE-SERVICE'
        environment: 
            # Important for clients to register with eureka
            - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            - spring.cloud.config.uri=http://config-server:9003

    user-service:
        container_name: user-service
        build:
            context: .
            dockerfile: ./user-service/user-service/Dockerfile
        image: user-service:latest
        expose:
            - 9004
        ports:
            - 9004:9004
        depends_on:
            - config-server
            - eureka-server
            - gateway-api
        logging:
            driver: json-file
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
            - eureka-server:eureka-server
            - gateway-api:gateway-api
        hostname: 'USER-SERVICE'
        environment: 
            # Important for clients to register with eureka
            - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            - spring.cloud.config.uri=http://config-server:9003

    webapp:
        container_name: webapp
        build:
            context: .
            dockerfile: ./webapp/Dockerfile
        image: webapp:latest

        expose:
            - 8080
        ports:
            - 8080:8080
        depends_on:
            - config-server
            - eureka-server
            - gateway-api
        logging:
            driver: json-file
        links:
            - config-server:config-server
            - eureka-server:eureka-server
            - route-service:route-service
            - parking-service:parking-service
            - user-service:user-service
            - gateway-api:gateway-api
        networks:
            - spring-cloud-network
        hostname: 'WEBAPP'
        environment: 
            # Important for clients to register with eureka
            - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            - spring.cloud.config.uri=http://config-server:9003

networks:
    spring-cloud-network:
        driver: bridge
